### ISSUE TITLE
esphome support

### ISSUE THREAD

**Issue by codegraffiti** [aZholtikov/zh_network#10]
Hi, is there are any plans to add support for [esphome](https://esphome.io/). It can be supported using [external components](https://esphome.io/components/external_components.html).
This would help to create home assistant compatible sensors, relays and other nodes very easily as esphome has an easy way to build nodes.

Best regards,
Chandan

**Comment by aZholtikov** [comment]
Hi Chandan!

ESPHome devices use WiFi connection to HA. ESP-NOW is a completely different technology. To support it, ESPHome developers need to change the code base, develop a gateway and make changes to the HA ESPHome integration.

It takes a big team, not one small enthusiast..... :-) And ESP-NOW isn't very common, so it'll probably never happen.
