### ISSUE TITLE
Maximum network bandwidth

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [aZholtikov/zh_network#11]
What is the maximum network bandwidth in your tests?

**Comment by aZholtikov** [comment]
Theoretically depends on the number of redirects. Each redirect takes about 20-30 milliseconds + 20-30 for a direct connection. Example - sending and receiving confirmation when sending through 2 intermediate devices will take approximately 60-90 milliseconds (assuming the route is already known). Under ideal conditions, with empty message queues in the devices and the same number of forwardings both from and to the destination. Maximum 218 bytes per message. 

In reality, a 500Kb transfer with 3 forwardings takes up to 5 minutes (in my network with 164 devices) during an OTA update.
P.S. Without OTA, it's about 200Kb per minute.

**Comment by NeKoRoM** [comment]
Hi @aZholtikov,

Thanks for the detailed breakdown of the latency and throughput!

Regarding the OTA updates you mentioned, do you happen to have a reference implementation or an example of how you handle OTA transfers over your network? I'm working on a similar setup and would love to see how you manage the chunking and delivery with these constraints.

Thanks in advance!

**Comment by aZholtikov** [comment]
Hi!

For example https://github.com/aZholtikov/zh_gateway as OTA Server + https://github.com/aZholtikov/zh_espnow_switch as OTA Client.

Implementation simply through ESP-NOW but it will also work through zh_network.
