### ISSUE TITLE
ESPNow-Mesh -> Connect to WiFi router with connection to internet ?

### ISSUE THREAD

**Issue by cherbin** [aZholtikov/zh_network#13]
I have ESPNow-Mesh running.

Is it possible for one of the nodes to connect to an external WiFi router which has connection to the internet ?

**Comment by aZholtikov** [comment]
Simultaneous operation of ESP-NOW (zh_network) and WiFI (internet connection) is possible. See https://github.com/aZholtikov/zh_gateway
