### ISSUE TITLE
Arduino supported version required

### ISSUE THREAD

**Issue by SethMSR1** [aZholtikov/zh_network#4]
Dear Team

Can we have a Arduino supported version of this library, Or how we can use this in arduino IDE.

Please suggest.

**Comment by aZholtikov** [comment]
Hi.

Please see https://github.com/aZholtikov/zh_network/issues/3
Use ZHNetwork version for Arduino.
Or I can mail you the branches with the arduino version of zh_network removed from the repository, but they are not recommended for use.

**Comment by SethMSR1** [comment]
Dear Alexy

I will be grateful if you can share the branches with the arduino version
of zh_network.

**Comment by aZholtikov** [comment]
Please send me any message to github@azholtikov.ru.
I will reply.

**Comment by aZholtikov** [comment]
In the attachment. But without any support now and in the future. Versions are not stable and not recommended for use.

[esp32.zip](https://github.com/aZholtikov/zh_network/files/14472002/esp32.zip)
[esp8266.zip](https://github.com/aZholtikov/zh_network/files/14472003/esp8266.zip)
