### ISSUE TITLE
Will ESP NOW Mesh Support 1000 nodes Connected in a line(Street Light) each 50-100 meter apart

### ISSUE THREAD

**Issue by mightChamp** [aZholtikov/zh_network#5]

**Comment by aZholtikov** [comment]
The 10km line formation has not been tested. Theoretically, there are no restrictions. You will have to proportionally increase the waiting time for a response.

ZHNetwork was tested on 10 devices in an area of approximately 120 square metres with 3 levels of forwarding maximum. The library is deprecated and is no longer supported.
zh_network was tested on 20 devices over an area of approximately 1 square kilometre with 5 forwarding levels maximum. About 130 devices are currently running smoothly.

**Comment by mightChamp** [comment]
@aZholtikov  Thanks for that, Could just me tell Will I choose this, Or Choose Zigbee Mesh?

**Comment by aZholtikov** [comment]
Depends on what you plan to do. If battery power is to be used, then zigbee. If external - then ESP-NOW can be used. If clients will never move, you can use a simpler (without routing) library painlessMesh. Or use zh_network to send only broadcast messages. All devices receive them and routing (and responce waiting time) is not important or used.

**Comment by aZholtikov** [comment]
https://forum.mysensors.org/topic/12127/zhnetwork-a-esp-now-based-mesh-network-for-esp8266-esp32-hardware

**Comment by mightChamp** [comment]
My System is as follows:
- AC Power Supply 24 Hours running
- Each Node is 50 Meter Apart on street light (last 1000th node is at 25km from gateway).
- Node will never move it is static
- Data Frame will be Max 50 Bytes
- Each node send Data to next 5 nodes, for some trigger.
- Each node send an heartbeat data to node every 15 minute.
- Gateway can send downlink for configurations any time.

So, Based on above could you suggest best Technology to use : 
      Zigbee/ESP-MDF/ESP-Mesh-Lite/PainlessMesh/ESP-NOW/zh_network/Openthread

**Comment by aZholtikov** [comment]
This is a very simple task, and I would suggest to use (from my point of view) a simple ESP-NOW without routing with only broadcast messages (of course, forwarding them from node to node). But don't forget to assign a sequence number to each device. Then there will be no dependency on MAC addresses in case of device failure. The devices will identify themselves by comparing their number and the number in the message.

A group firmware update of all identical devices is also possible via ESP-NOW.

**Comment by aZholtikov** [comment]
Contact me by e-mail if necessary. Regarding ESP-NOW of course. I have studied it quite a bit and know some subtleties not described in the documentation.
